version: "3"
services:
  mariadb:
    restart: always
    image: mariadb
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi

  strapi:
    restart: always
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mariadb
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: "false"
    volumes:
      - ./app:/srv/app
    ports:
      - "1337:1337"
    depends_on:
      - mariadb

  phpmyadmin:
    restart: always
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mariadb
      - PMA_ARBITRARY=1
    depends_on:
      - mariadb
