# https://doc.traefik.io/traefik/user-guides/docker-compose/acme-tls/

version: "3.3"

services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./volumes/strapi/app:/srv/app
    ports:
      - "1337:1337"
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.restaurant_strapi.rule=Host(`restaurant_strapi.iamon99.com`)"
      - "traefik.http.routers.restaurant_strapi.entrypoints=websecure"
      - "traefik.http.routers.restaurant_strapi.tls.certresolver=myresolver"
      - "traefik.http.services.restaurant_strapi.loadbalancer.server.port=1337"

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./volumes/strapi/data:/var/lib/postgresql/data

networks:
  default:
    external:
      name: traefik-proxy-network
